### ISSUE TITLE
Definir instrucciones del API desde el html

### ISSUE THREAD

**Issue by tripplab** [tripplab/HTMoLv3.5#3]
Modificar código para que se puedan definir instrucciones del API desde el html (por ejemplo ver view-source:https://chemapps.stolaf.edu/jmol/jsmol/jsmol.htm):
```
<script type="text/javascript">
script: "set zoomlarge false;set antialiasDisplay;" 
</script>
``` 
como en https://chemapps.stolaf.edu/jmol/jsmol/jsmol.htm?_USE=HTML5
Así, dentro del html se podrán definir instrucciones, como selecciones, cambios de color y representación, acercamientos de cámara, etc. de forma programática, por ejemplo automáticamente:
`'select *; cartoons off; spacefill only'`

o también con un link en la página que el usuario de click para que se ejecute:

`<a href="javascript:Jmol.script(jmolApplet0,'select *; cartoons off; spacefill only')">spacefill</a>`

**Comment by leoalvriv** [comment]
se implementó con una variable llamada "commandsDefault", cada instrucción separada por un ";"
ejemplo ;
var commandsDefault="select 1-60;show CPK;select 200-240;show CPK;color blue";

**Comment by leoalvriv** [comment]
A continuación se señalan las modificaciones realizadas en los distintos archivos:
ARCHIVOS MODIFICADOS:
config.js
La variable “RepresentacionInicial” (especifica que representación será cargada por defecto) fue cambiada a otro archivo así como también la variables “pdbInicial”  y "xtcInicial"(señala que archivo pdb es cargado desde el inicio). 
HTMoL.html
Las variables “RepresentacionInicial”, “xtcInicial” y “pdbInicial” fueron agregadas en este archivo como parte de realizar configuraciones se forma más sencilla a HTMoL. 
Se integró la variable “commandsDefault” donde se establecen los comandos que se ejecutará HTMoL en la molécula al momento que la página sea cargada inicialmente.
Ejemplo: ”select 1-60;show CPK;select 200-cpk;color red”
InicializarRepre.js
Se agregó la función “InitBufRepreDefault” la cual recibe la cadena de comandos, en dicha cadena los comandos están separados por “;” de esta forma pueden ser separados y ejecutados individualmente (si un comando está mal escrito es ignorado).
MainHTMoL.js
Se llama a “InitBufRepreDefault” en la función webGLStart con la variable commandsDefault como parámetro.
